#' .. content for \description{} (no empty lines) ..
#'
#' .. content for \details{} ..
#'
#' @title
#' @param schema_extract
#' @param wahis_tables
#' @return
#' @author Emma Mendelsohn
#' @export
process_schema <- function(schema_extract, wahis_tables, disease_key) {

  schema_extract <- schema_extract |>
    janitor::clean_names() |>
    mutate_if(is.character, tolower)  |>
    mutate(field = janitor::make_clean_names(field))

  wahis_epi_event_schema <- tibble(field = colnames(wahis_tables$wahis_epi_event),
                                   field_type = map_chr(wahis_tables$wahis_epi_event, ~class(.)[1])) |>
    left_join(schema_extract) |>
    mutate(table = "wahis_epi_event") |>
    relocate(table, .before = everything()) |>
    mutate(primary_key = ifelse(field == "epi_event_id", "*", "")) |>
    mutate(foreign_key = ifelse(field == "epi_event_id", "epi_event_id in wahis_outbreaks (one to many)", ""))

  wahis_outbreaks_schema <- tibble(field = colnames(wahis_tables$wahis_outbreaks),
                                   field_type = map_chr(wahis_tables$wahis_outbreaks, ~class(.)[1])) |>
    left_join(schema_extract) |>
    mutate(table = "wahis_outbreaks") |>
    relocate(table, .before = everything()) |>
    mutate(field_description = case_when(field == "unique_id" ~ "unique combination of report_id, outbreak_id, and species (this field is generated by EHA)",
                                         .default = field_description)) |>
    mutate(primary_key = ifelse(field == "unique_id", "*", "")) |>
    mutate(foreign_key = ifelse(field == "epi_event_id", "epi_event_id in wahis_epi_event (many to one)", ""))


  disease_key_schema <- tibble(field = colnames(disease_key),
                              field_type = map_chr(disease_key, ~class(.)[1])) |>
    mutate(descripton = c("disease name following ANDO standardization (this is an intermediary state)",
                          "cleaned/standardized disease name",
                          "data source `wahis`",
                          "alternate name for disease",
                          "pathogen taxonomy group (`bacteria`,  `virus`,  `eukaryote`, `prion`,  NA)",
                          "pathogen taxonomy order",
                          "pathogen taxonomy family",
                          "pathogen taxonomy genus",
                          "pathogen taxonomy species",
                          "pathogen name abbreviation",
                          "additional information on the disease",
                          "additional information on the disease",
                          "additional information on the disease",
                          "pathogen vector if applicable") ) |>
    mutate(primary_key = ifelse(field == "disease", "*", "")) |>
    mutate(foreign_key = ifelse(field == "disease", "disease in wahis_epi_event (many to one)", ""))



  schema <- bind_rows(wahis_epi_event_schema, wahis_outbreaks_schema) |>
    mutate(id = row_number()) |>
    relocate(id, .before = everything())

  return(schema)

}
