#' .. content for \description{} (no empty lines) ..
#'
#' .. content for \details{} ..
#'
#' @title
#' @param schema_extract
#' @param outbreak_events_tables
#' @return
#' @author Emma Mendelsohn
#' @export
process_schema <- function(schema_extract,
                           outbreak_events_tables,
                           six_month_status_tables,
                           six_month_controls_tables,
                           six_month_quantitative_tables,
                           disease_key,
                           taxon_key) {

  # schema extract from wahis for outbreak/events table
  schema_extract <- schema_extract |>
    janitor::clean_names() |>
    mutate_if(is.character, tolower)  |>
    mutate(field = janitor::make_clean_names(field))

  ### disease key
  disease_key_schema <- tibble(field = colnames(disease_key)) |>
    mutate(field_type = "character") |>
    mutate(field_descripton = c("raw disease name as it appears in outbreak or six month tables",
                                "cleaned/standardized disease name",
                                "pathogen taxonomy group (`bacteria`,  `virus`,  `eukaryote`, `prion`,  NA)",
                                "pathogen taxonomy order",
                                "pathogen taxonomy family",
                                "pathogen taxonomy genus",
                                "pathogen taxonomy species",
                                "pathogen name abbreviation",
                                "additional information on the disease",
                                "additional information on the disease",
                                "additional information on the disease",
                                "pathogen vector if applicable")) |>
    mutate(primary_key = case_when(field == "disease" ~ "*", .default =  "")) |>
    mutate(foreign_key = case_when(field == "standardized_disease_name" ~ "one to many for all events and six month tables",
                                   .default = "")) |>
    mutate(generated_field = TRUE)

  ### taxon key
  taxon_key_schema <- tibble(field = colnames(taxon_key)) |>
    mutate(field_type = "character") |>
    mutate(field_descripton = c("raw taxon/species name as it appears in outbreak or six month tables",
                                "cleaned/standardized taxon name",
                                "common name",
                                "pathogen taxonomy class",
                                "pathogen taxonomy order",
                                "pathogen taxonomy family",
                                "pathogen taxonomy genus",
                                "pathogen taxonomy species",
                                "standardization notes")) |>
    mutate(primary_key = case_when(field == "taxon" ~ "*", .default =  "")) |>
    mutate(foreign_key = case_when(field == "standardized_taxon_name" ~ "one to many for all events and six month tables (except `wahis_epi_events`)",
                                   .default = "")) |>
    mutate(generated_field = TRUE)


  ### wahis_epi_events
  wahis_epi_events_schema <- tibble(table = "wahis_epi_events",
                                    field = colnames(outbreak_events_tables$events),
                                    field_type = map_chr(outbreak_events_tables$events, ~class(.)[1])) |>
    mutate(field_raw = unname(outbreak_events_tables$outbreak_events_schema_raw[field])) |>
    left_join(schema_extract) |>
    mutate(field_description = case_when(field == "epi_event_id_unique" ~ "for most events, this is the same as epi_event_id. for events with reporting by strain or serotype, the epi_event_id is combined with the strain or serotype (this field is generated by EHA)",
                                         field == "standardized_disease_name" ~ "cleaned/standardized disease name",
                                         .default = field_description)) |>
    mutate(primary_key = case_when(field == "epi_event_id_unique" ~ "*", .default = "")) |>
    mutate(foreign_key = case_when(field == "epi_event_id_unique" ~ "epi_event_id_unique in wahis_outbreaks (one to many)",
                                   field == "epi_event_id" ~ "epi_event_id in wahis_six_month_quantitative (one to many)",
                                   field == "standardized_disease_name" ~ "standardized_disease_name in disease_key (many to one)",
                                   .default = "")) |>
    mutate(generated_field = field %in% c("epi_event_id_unique", "standardized_disease_name"))

  ### wahis_outbreaks
  wahis_outbreaks_schema <- tibble(table = "wahis_outbreaks",
                                   field = colnames(outbreak_events_tables$outbreaks),
                                   field_type = map_chr(outbreak_events_tables$outbreaks, ~class(.)[1])) |>
    mutate(field_raw = unname(outbreak_events_tables$outbreak_events_schema_raw[field])) |>
    left_join(schema_extract) |>
    mutate(field_description = case_when(field == "report_outbreak_species_id_unique" ~ "unique combination of report_id, outbreak_id, and species (this field is generated by EHA)",
                                         field == "epi_event_id_unique" ~ "for most events, this is the same as epi_event_id. for events with reporting by strain or serotype, the epi_event_id is combined with the strain or serotype (this field is generated by EHA)",
                                         field == "standardized_disease_name" ~ "cleaned/standardized disease name",
                                         field == "standardized_taxon_name" ~ "cleaned/standardized taxon name",
                                         .default = field_description)) |>
    mutate(primary_key = case_when(field == "report_outbreak_species_id_unique" ~ "*", .default =  "")) |>
    mutate(foreign_key = case_when(field == "epi_event_id_unique" ~ "epi_event_id_unique in wahis_epi_events (many to one)",
                                   field == "standardized_disease_name" ~ "standardized_disease_name in disease_key (many to one)",
                                   field == "standardized_taxon_name" ~ "standardized_taxon_name in taxon_key (many to one)",
                                   .default = "")) |>
    mutate(generated_field = field %in% c("epi_event_id_unique", "report_outbreak_species_id_unique", "standardized_disease_name", "standardized_taxon_name"))


  ### wahis_six_month_status
  wahis_six_month_status_schema <- tibble(table = "wahis_six_month_status",
                                          field = colnames(six_month_status_tables$table),
                                          field_type = map_chr(six_month_status_tables$table, ~class(.)[1])) |>
    mutate(field_raw = unname(six_month_status_tables$schema_raw[field])) |>
    left_join(schema_extract) |> # not much overlap
    mutate(field_description = case_when(field == "six_month_status_unique_id" ~ "unique id from concatenation of year, semester_code, country, disease, animal_category",
                                         field == "year" ~ "report year",
                                         field == "semester" ~ "jan-jun or jul-dec",
                                         field == "world_region" ~ "geographical region (renamed from region in wahis to match quantitative data)",
                                         field == "disease" ~ "disease name",
                                         field == "disease_status" ~ "disease status",
                                         field == "occurence_code" ~ "disease status with slightly more detail",
                                         field == "animal_category" ~ "domestic or wild",
                                         field == "semester_code" ~ "1 for jan-jun and 2 for jul-dec",
                                         field == "standardized_disease_name" ~ "cleaned/standardized disease name",
                                         field == "standardized_taxon_name" ~ "cleaned/standardized taxon name",
                                         .default = field_description)) |>
    mutate(primary_key = ifelse(field == "six_month_status_unique_id", "*", "")) |>
    mutate(foreign_key = case_when(field == "standardized_disease_name" ~ "standardized_disease_name in disease_key (many to one)",
                                   field == "standardized_taxon_name" ~ "standardized_taxon_name in taxon_key (many to one)",
                                   .default = "")) |>
    mutate(generated_field = field %in% c("six_month_status_unique_id","semester_code", "standardized_disease_name", "standardized_taxon_name"))

  ### wahis_six_month_controls
  wahis_six_month_controls_schema <- tibble(table = "wahis_six_month_controls",
                                            field = colnames(six_month_controls_tables$table),
                                            field_type = map_chr(six_month_controls_tables$table, ~class(.)[1])) |>
    mutate(field_raw = unname(six_month_controls_tables$schema_raw[field])) |>
    left_join(schema_extract) |> # not much overlap
    mutate(field_description = case_when(field == "six_month_controls_unique_id" ~  "unique id from concatenation of year, semester_code, country,disease, animal_category, species, control_measure_code",
                                         field == "year" ~ "report year",
                                         field == "semester" ~ "jan-jun or jul-dec",
                                         field == "world_region" ~ "geographical region (renamed from region in wahis to match quantitative data)",
                                         field == "disease" ~ "disease name",
                                         field == "control_measure" ~ "type of control measure applied",
                                         field == "animal_category" ~ "domestic or wild",
                                         field == "semester_code" ~ "1 for jan-jun and 2 for jul-dec",
                                         field == "control_measure_code" ~ "numeric code identifier for each unique type of control measure",
                                         field == "standardized_disease_name" ~ "cleaned/standardized disease name",
                                         field == "standardized_taxon_name" ~ "cleaned/standardized taxon name",
                                         .default = field_description)) |>
    mutate(primary_key = ifelse(field == "six_month_controls_unique_id", "*", "")) |>
    mutate(foreign_key = case_when(field == "standardized_disease_name" ~ "standardized_disease_name in disease_key (many to one)",
                                   field == "standardized_taxon_name" ~ "standardized_taxon_name in taxon_key (many to one)",
                                   .default = "")) |>
    mutate(generated_field = field %in% c("six_month_controls_unique_id","semester_code", "control_measure_code", "standardized_disease_name", "standardized_taxon_name"))

  ### wahis_six_month_quantitative
  wahis_six_month_quantitative_schema <- tibble(table = "wahis_six_month_quantitative",
                                                field = colnames(six_month_quantitative_tables$table),
                                                field_type = map_chr(six_month_quantitative_tables$table, ~class(.)[1])) |>
    mutate(field_raw = unname(six_month_quantitative_tables$schema_raw[field])) |>
    left_join(schema_extract) |> # not much overlap
    mutate(field_description = case_when(field == "six_month_quantitative_unique_id" ~  "unique id from concatenation of year, semester_code, country, disease, serotype_subtype_genotype, animal_category, species, outbreak_id, administrative_division",
                                         field == "year" ~ "report year",
                                         field == "semester" ~ "jan-jun or jul-dec",
                                         field == "world_region" ~ "geographical region (renamed from region in wahis to match quantitative data)",
                                         field == "disease" ~ "disease name",
                                         field == "control_measure" ~ "type of control measure applied",
                                         field == "animal_category" ~ "domestic or wild",
                                         field == "semester_code" ~ "1 for jan-jun and 2 for jul-dec",
                                         field == "standardized_disease_name" ~ "cleaned/standardized disease name",
                                         field == "standardized_taxon_name" ~ "cleaned/standardized taxon name",
                                         field == "administrative_division" ~ "geographic location of outbreak (subcountry level)", # probably has an overlap in outbreak table
                                         field == "serotype_subtype_genotype" ~ "name of the serotype/subtype/genotype in english (if provided)", # sero_sub_genotype_eng in epi event table
                                         field == "new_outbreaks" ~ "number of new outbreaks",
                                         field == "measuring_units" ~ "unit of counting cases", # quantitative_unit in outbreak table
                                         field == "killed_and_disposed_of" ~ "number of units of animals killed and disposed of in the outbreak/cluster", # killed_disposed in outbreak table
                                         field == "deaths" ~ "number of units of dead animals in the outbreak/cluster", # dead in outbreak table
                                         .default = field_description)) |>
    mutate(primary_key = ifelse(field == "six_month_quantitative_unique_id", "*", "")) |>
    mutate(foreign_key = case_when(field == "standardized_disease_name" ~ "standardized_disease_name in disease_key (many to one)",
                                   field == "standardized_taxon_name" ~ "standardized_taxon_name in taxon_key (many to one)",
                                   field == "epi_event_id" ~ "epi_event_id in wahis_epi_events (many to one)",
                                   .default = "")) |>
    mutate(generated_field = field %in% c("six_month_quantitative_unique_id","semester_code", "standardized_disease_name",  "standardized_taxon_name"))

  ### Full schema
  schema <- bind_rows(wahis_epi_events_schema, wahis_outbreaks_schema, wahis_six_month_status_schema, wahis_six_month_controls_schema, wahis_six_month_quantitative_schema) |>
    mutate(id = row_number()) |>
    relocate(id, .before = everything())

  assert_that(all(!is.na(schema$field_description)))

  return(schema)

}
