#'
#' Get current fields names of various dataset inputs
#'
#'
#'
#'
#'
create_data_fields_reference <- function(outbreak_events_extract,
                                         six_month_status_extract,
                                         six_month_controls_extract,
                                         six_month_quantitative_extract) {
  df <- rbind(
    data.frame(
      table_name = "outbreak_events_extract",
      field_name = outbreak_events_extract |> janitor::clean_names() |> names()
    ),
    data.frame(
      table_name = "six_month_status_extract",
      field_name = six_month_status_extract |> janitor::clean_names() |> names()
    ),
    data.frame(
      table_name = "six_month_controls_extract",
      field_name = six_month_controls_extract |> janitor::clean_names() |> names()
    ),
    data.frame(
      table_name = "six_month_quantitative_extract",
      field_name = six_month_quantitative_extract |> janitor::clean_names() |> names()
    )
  )

  write.csv(
    x = df,
    file = file.path(
      "checks",
      paste0("data_fields_reference_", Sys.Date(), ".csv")
    ),
    row.names = FALSE
  )

  file.path("checks", paste0("data_fields_reference_", Sys.Date(), ".csv"))
}


#'
#' Check current reference fields to most recent reference field
#'
#' @param current A data.frame for most current field names reference.
#' @param previous A data.frame for previous filed names reference.
#' @param data_fields_reference_file File path for most current field names
#'   CSV file. This is usually generated by the target with the same name.
#'
#' @returns Either a message confirming that the dataset field names haven't
#'   changed or an error message saying that the dataset field names have
#'   changed.
#'
#' @examples
#' data_check_fields(data_fields_reference_file)
#'
#' @export
#'
check_data_field <- function(current, previous) {
  if (!any(previous$field_name %in% current$field_name)) {
    stop(
      paste0(
        "Currently available *", unique(current$table_name),
        "* dataset does not have all the expected field names. Please verify and adjust processing functions accordingly."
      )
    )
  } else {
    message(
      paste0(
        "Currently available *", unique(current$table_name),
        "* dataset has all the expected field names."
      )
    )
  }
}




check_data_fields <- function(data_fields_reference_file) {
  ## Read current reference file ----
  current <- read.csv(data_fields_reference_file) |>
    split(f = ~table_name)

  ## Get previous file ----
  previous <- list.files("checks", full.names = TRUE) |>
    rev() |>
    (\(x) x[2])() |>
    read.csv() |>
    split(f = ~table_name)

  ## Compare fields ----
  Map(
    f = check_data_field,
    previous = previous,
    current = current
  )
}


