#'
#' Get current fields names of various dataset inputs
#'
#' @param outbreak_events_extract Data.frame containing outbreak events from
#'   WAHIS.
#' @param six_month_status_extract Data.frame containing six month outbreak
#'   status from WAHIS. Currently, this is downloaded from the WOAH dashboard.
#' @param six_month_controls_extract Data.frame containing six month outbreak
#'   control measures from WAHIS. Currently, this is downloaded from the WOAH
#'   dashboard.
#' @param six_month_quantitative_extract Data.frame containing six month
#'   outbreak numbers/figures from WAHIS. Currently, this is downloaded from
#'   the WOAH dashboard.
#'
#' @returns A file path to a created CSV file of field names found in each of
#'   the input data.frames.
#'
#' @examples
#' create_data_fields_reference(
#'   outbreak_events_extract, six_month_status_extract,
#'   six_month_controls_extract, six_month_quantitative_extract
#' )
#'
#' @export
#'
create_data_fields_reference <- function(outbreak_events_extract,
                                         six_month_status_extract,
                                         six_month_controls_extract,
                                         six_month_quantitative_extract) {
  df <- rbind(
    data.frame(
      table_name = "outbreak_events_extract",
      field_name = outbreak_events_extract |> janitor::clean_names() |> names()
    ),
    data.frame(
      table_name = "six_month_status_extract",
      field_name = six_month_status_extract |> janitor::clean_names() |> names()
    ),
    data.frame(
      table_name = "six_month_controls_extract",
      field_name = six_month_controls_extract |> janitor::clean_names() |> names()
    ),
    data.frame(
      table_name = "six_month_quantitative_extract",
      field_name = six_month_quantitative_extract |> janitor::clean_names() |> names()
    )
  )

  write.csv(
    x = df,
    file = file.path(
      "checks",
      paste0("data_fields_reference_", Sys.Date(), ".csv")
    ),
    row.names = FALSE
  )

  file.path("checks", paste0("data_fields_reference_", Sys.Date(), ".csv"))
}


#'
#' Check current reference fields to most recent reference field
#'
#' @param current A data.frame for most current field names reference.
#' @param previous A data.frame for previous filed names reference.
#' @param data_fields_reference_file File path for most current field names
#'   CSV file. This is usually generated by the target with the same name.
#'
#' @returns Either a message confirming that the dataset field names haven't
#'   changed or an error message saying that the dataset field names have
#'   changed.
#'
#' @examples
#' data_check_fields(data_fields_reference_file)
#'
#' @rdname check_data_field
#' @export
#'
check_data_field <- function(current, previous) {

  previous_not_current <- setdiff(previous$field_name, current$field_name)
  current_not_previous <- setdiff(current$field_name, previous$field_name)

  if (length(previous_not_current)) {
    stop(
      glue::glue(
        "Currently available *{unique(current$table_name)}* is missing expected field names: {paste(previous_not_current, collapse = ', ')}.
        Please verify and adjust processing functions accordingly."
      )
    )
  }

  if (length(current_not_previous)) {
    warning(
      glue::glue(
        "Currently available *{unique(current$table_name)}* has new field: {paste(current_not_previous, collapse = ', ')}.
        You may need to verify and adjust processing functions accordingly."
      )
    )
  } else {
    message(
      paste0(
        "Currently available *", unique(current$table_name),
        "* dataset has all the expected field names."
      )
    )
  }
}


#'
#' @rdname check_data_field
#' @export
#'
check_data_fields <- function(data_fields_reference_file) {
  ## Read current reference file ----
  current <- read.csv(data_fields_reference_file) |>
    split(f = ~table_name)

  ## Get previous file ----
  previous <- list.files("checks", full.names = TRUE) |>
    rev() |>
    (\(x) x[2])() |>
    read.csv() |>
    split(f = ~table_name)

  ## Compare fields ----
  Map(
    f = check_data_field,
    previous = previous,
    current = current
  )
}

#'
#' Read and check provided/downloaded XLSX files from WAHIS
#'
#' @param path_to_xlsx File path to XSLX file for the WAHIS dataset that is to
#'   be read.
#' @param sheet Sheet number or sheet name to read from the XLSX file in
#'   `path_to_xlsx`.
#' @param df Tag name for the WAHIS dataset to be read. This can be either
#'   `events` for the outbreak events data, `status` for the outbreak
#'   status data, `controls` for the outbreak control measures data, or
#'   `quantitative` for the outbreak figures/numbers data.
#'
#' @returns A tibble of the specified dataset. A message or an error will also
#'   be printed depending on whether the dataset has the expected field names
#'   as previous datasets. If an error occurs, an error message will be printed
#'   but the reading of the dataset will still be done and returned.
#'
#' @examples
#' read_wahis_dataset(outbreak_events_file, sheet = 2, df = "events")
#' read_wahis_dataset(six_month_status_file, sheet = 1, df = "status")
#'
#' @export
#'
#'
read_wahis_dataset <- function(path_to_xlsx,
                               sheet,
                               df = c("events", "status",
                                      "controls", "quantitative")) {
  ## What dataset is this?
  df <- match.arg(df)

  df <- switch(
    df,
    events = "outbreak_events_extract",
    status = "six_month_status_extract",
    controls = "six_month_controls_extract",
    quantitative = "six_month_quantitative_extract"
  )

  wahis_df <- readxl::read_excel(path = path_to_xlsx, sheet = sheet)

  current <- data.frame(
    table_name = df,
    field_name = wahis_df |>
      janitor::clean_names() |>
      names()
  )

  previous <- list.files("checks", full.names = TRUE) |>
    rev() |>
    (\(x) x[2])() |>
    read.csv() |>
    dplyr::filter(table_name == df)

  ## Check dataaset ----
  try(check_data_field(current, previous))

  ## Return WAHIS dataset ----
  wahis_df
}

